services:
  app:
    build: .
    container_name: batcom
    platform: linux/amd64
    image: vukilelanga/batcom:2025.10.23-2
    ports:
      - ${PORT:-3000}:3000
    command: >
      sh -c "NODE_TLS_REJECT_UNAUTHORIZED=0 npx drizzle-kit push && node dist/index.js"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: ${NODE_ENV:-development}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_CA_CERT: ${POSTGRES_CA_CERT}
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    # restart: unless-stopped
    # depends_on:
    #   - db
#   db:
#     container_name: batcom-db
#     image: postgres:17
#     environment:
#       POSTGRES_USER: batcomuser
#       POSTGRES_PASSWORD: batcompassword
#       POSTGRES_DB: batcom
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
# db:
